version: '3.5'

services:
  safeNatureApi:
    container_name: safeNatureApi
    image: sairan/safenatureapi:latest
    restart: always
    env_file:
      - stack.env
    ports:
      - 8888:80
    networks:
      - mysql-network
      - proxy-reverse-network

  safeNatureCronJon:
  container_name: safeNatureCronJon
  image: sairan/safenatureapi:latest
  restart: always
  env_file:
    - stack.env
  ports:
    - 9999:80
  networks:
    - mysql-network
    - proxy-reverse-network

networks:
  mysql-network:
    driver: bridge
  proxy-reverse-network:
    driver: bridge
