version: "3.5"

services:
  safeNatureApi:
   build: .
   container_name: safeNatureApi
   ports:
    - "8888:8888"
   restart: always

   volumes:
    - .:/app/safeNatureApi
    - vendor-safeNatureApi:/app/safeNatureApi/vendor
   networks:
    - conection-netowork
   depends_on:
    - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: safeNature
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - conection-netowork


networks:
  conection-netowork:
   name: conection-netowork
   driver: bridge

volumes:
  vendor-safeNatureApi:
    name: vendor-safeNatureApi

  mysqldata:
