version: "3.5"

services:
  safe-nature:
   build: .
   container_name: safeNatureApi
   ports:
    - "8888:8888"
   restart: always
   extra_hosts:
    - mysql:127.0.0.1
    - mysql-prod:195.35.19.131

   volumes:
    - .:/app/safeNatureApi
    - vendor-safeNatureApi:/app/safeNatureApi/vendor
   networks:
    - conection-network
   stdin_open: true
   tty: true
#    depends_on:
#     - mysql

#   mysql:
#     image: mysql:latest
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: safeNature
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysqldata:/var/lib/mysql
#     networks:
#       - conection-netowork


networks:
  conection-network:
   name: conection-network
   driver: bridge

volumes:
  vendor-safeNatureApi:
    name: vendor-safeNatureApi

  mysqldata:
