version: '3.5'

services:
  safeNatureApi:
    container_name: safeNatureApi
    image: sairan/safenatureapi:latest
    restart: always
    env_file:
      - stack.env
    ports:
      - 8888:80
    networks:
      - mysql-network
      - proxy-reverse-network

  networks:
    mysql-network:
     name: mysql-network
     driver: bridge

    proxy-reverse-network:
     name: proxy-reverse-network
     driver: bridge
