version: '3.5'

services:
  safeNatureApi:
    container_name: safeNatureApi
    image: sairan/safenatureapi:latest
    restart: always
    env_file:
      - stack.env
    ports:
      - 8888:80
    networks:
      - mysql-network
      - proxy-reverse-network

  safeNatureCronJob:
    container_name: safeNatureCronJob
    image: sairan/safenaturecronjob:latest
    restart: always
    command: ["php artisan schedule:run"]
    env_file:
      - stack.env
    ports:
      - 9999:80
    networks:
      - mysql-network
      - proxy-reverse-network

networks:
  mysql-network:
    driver: bridge
  proxy-reverse-network:
    driver: bridge
